'''#!/usr/bin/env python
"""Extract all questions for JEE Main, JEE Advanced, NDA from ExamGoal.
The script loads test IDs from paper_list.json (generated by full_scraper.py),
uses fresh login cookies (test_cookies.json), and fetches each test's question IDs.
Then it retrieves each question via the /past-question/question/{qid} endpoint
and saves the full question data into exam-specific JSON files under the
`questions/` directory.
"""
import json, os, time, sys
import requests

BASE = "https://room.examgoal.com/api/v1"
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "eg-app-id": "room-examgoal-com",
    "eg-platform": "desktop",
    "Referer": "https://room.examgoal.com/",
    "accept": "application/json",
}

# Load cookies saved by fresh_login_test.py
cookies_path = os.path.join(os.path.dirname(__file__), "test_cookies.json")
if not os.path.exists(cookies_path):
    print("Cookie file not found. Run fresh_login_test.py first.")
    sys.exit(1)
with open(cookies_path, "r", encoding="utf-8") as f:
    raw_cookies = json.load(f)
session = requests.Session()
for c in raw_cookies:
    session.cookies.set(c["name"], c["value"], domain=c.get("domain", "room.examgoal.com"))

# Load paper list generated by full_scraper.py
papers_path = os.path.join(os.path.dirname(__file__), "paper_list.json")
if not os.path.exists(papers_path):
    print("Paper list not found. Run full_scraper.py first.")
    sys.exit(1)
with open(papers_path, "r", encoding="utf-8") as f:
    papers = json.load(f)

# Ensure output directory
out_dir = os.path.join(os.path.dirname(__file__), "questions")
os.makedirs(out_dir, exist_ok=True)

for exam, paper_list in papers.items():
    all_questions = []
    print(f"Processing exam: {exam} ({len(paper_list)} papers)")
    for paper in paper_list:
        test_id = paper.get("testId")
        if not test_id:
            continue
        # Try the personalized test endpoint first
        url = f"{BASE}/past-question/tests/personalized/test/{test_id}"
        resp = session.get(url, headers=HEADERS, timeout=15)
        data = None
        if resp.status_code == 200:
            try:
                data = resp.json()
            except Exception:
                data = None
        # Fallback to generic test endpoint
        if not data:
            resp = session.get(f"{BASE}/test/{test_id}", headers=HEADERS, timeout=15)
            if resp.status_code == 200:
                try:
                    data = resp.json()
                except Exception:
                    data = None
        if not data:
            print(f"  Unable to fetch test data for {test_id}, status {resp.status_code}")
            continue
        # Extract question IDs
        qids = []
        for field in ["questionIds", "questions", "items", "data"]:
            if field in data:
                val = data[field]
                if isinstance(val, list):
                    if val and isinstance(val[0], str):
                        qids = val
                    elif val and isinstance(val[0], dict):
                        qids = [q.get("id") or q.get("questionId") for q in val]
                break
        if not qids:
            print(f"  No question IDs found in test {test_id}")
            continue
        print(f"  Test {test_id}: {len(qids)} questions")
        for qid in qids:
            if not qid:
                continue
            qresp = session.get(f"{BASE}/past-question/question/{qid}", headers=HEADERS, timeout=15)
            if qresp.status_code == 200:
                try:
                    qdata = qresp.json()
                    if qdata.get("statusCode") == 0:
                        all_questions.append(qdata.get("data", {}))
                except Exception:
                    pass
            # Throttle a bit to avoid hammering the server
            time.sleep(0.1)
    # Save exam questions
    out_path = os.path.join(out_dir, f"{exam}_questions.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(all_questions, f, ensure_ascii=False, indent=2)
    print(f"Saved {len(all_questions)} questions for {exam} to {out_path}\n")

print("Extraction complete.")
'''
