const MAP = {
  "Quadratic Equation and Inequalities": "ch_adv_mathematics_0",
  "Sequences and Series": "ch_adv_mathematics_1",
  "Mathematical Induction and Binomial Theorem": "ch_adv_mathematics_2",
  "Matrices and Determinants": "ch_adv_mathematics_3",
  "Permutations and Combinations": "ch_adv_mathematics_4",
  "Probability": "ch_adv_mathematics_5",
  "Vector Algebra": "ch_adv_mathematics_6",
  "3D Geometry": "ch_adv_mathematics_7",
  "Statistics": "ch_adv_mathematics_8",
  "Complex Numbers": "ch_adv_mathematics_9",
  "Trigonometric Functions & Equations": "ch_adv_mathematics_10",
  "Inverse Trigonometric Functions": "ch_adv_mathematics_11",
  "Properties of Triangle": "ch_adv_mathematics_12",
  "Straight Lines and Pair of Straight Lines": "ch_adv_mathematics_13",
  "Circle": "ch_adv_mathematics_14",
  "Parabola": "ch_adv_mathematics_15",
  "Ellipse": "ch_adv_mathematics_16",
  "Hyperbola": "ch_adv_mathematics_17",
  "Functions": "ch_adv_mathematics_18",
  "Limits, Continuity and Differentiability": "ch_adv_mathematics_19",
  "Differentiation": "ch_adv_mathematics_20",
  "Application of Derivatives": "ch_adv_mathematics_21",
  "Indefinite Integrals": "ch_adv_mathematics_22",
  "Definite Integration": "ch_adv_mathematics_23",
  "Application of Integration": "ch_adv_mathematics_24",
  "Differential Equations": "ch_adv_mathematics_25"
};
module.exports = MAP;