const fs = require('fs');
const path = 'C:/Users/Admin/.gemini/antigravity/scratch/quantrexacadmy/src/pages/StudentDashboard.jsx';
const lines = fs.readFileSync(path, 'utf8').split('\n');

const newLines = lines.slice(0, 510);
newLines.push('                          <div className="h-12 w-12 bg-white/5 rounded-full flex items-center justify-center text-gray-500">');
newLines.push('                            <BookOpen className="h-5 w-5" />');
newLines.push('                          </div>');
newLines.push('                          <p className="text-xs text-gray-500 font-mono">Select a chapter from the left menu to view contents.</p>');
newLines.push('                        </div>');
newLines.push('                      )}');
newLines.push('                    </div>');
newLines.push('                  </div>');
newLines.push('              </div>');
newLines.push('            )}');
newLines.push('');
newLines.push('            {/* LIVE CLASSES TAB */}');
newLines.push('            {activeTab === \'live\' && (');
newLines.push('              <div className="space-y-6">');
newLines.push('                <h3 className="text-xl font-bold text-white uppercase tracking-wider font-display">Upcoming Schedules</h3>');
newLines.push('                <div className="space-y-4">');
newLines.push('                  {[');
newLines.push('                    { title: \'Calculus Advanced Problem Solving\', time: \'Today at 6:00 PM\', status: \'Live In 2 Hrs\', instructor: \'Ajay Kumar Saroj\' },');
newLines.push('                    { title: \'Vector Geometry Coordinate Shifts\', time: \'Tomorrow at 4:30 PM\', status: \'Scheduled\', instructor: \'Ajay Kumar Saroj\' }');
newLines.push('                  ].map((c, idx) => (');
newLines.push('                    <div key={idx} className="p-5 bg-cyberdark border border-white/5 rounded-xl flex flex-wrap items-center justify-between gap-4">');
newLines.push('                      <div className="space-y-1">');
newLines.push('                        <h4 className="text-white font-bold text-sm">{c.title}</h4>');
newLines.push('                        <p className="text-xs text-gray-500 font-mono">Instructor: {c.instructor} • {c.time}</p>');
newLines.push('                      </div>');
newLines.push('                      <span className={`text-[10px] font-bold font-mono px-3 py-1 rounded ${idx === 0 ? \'bg-red-500/10 border border-red-500/30 text-red-400 animate-pulse\' : \'bg-white/5 border border-white/10 text-gray-400\'}`}>');
newLines.push('                        {c.status}');
newLines.push('                      </span>');
newLines.push('                    </div>');
newLines.push('                  ))}');
newLines.push('                </div>');
newLines.push('              </div>');
newLines.push('            )}');
newLines.push('');
newLines.push('            {/* MOCK TESTS TAB */}');
newLines.push('            {activeTab === \'tests\' && (');
newLines.push('              <div className="space-y-6">');
newLines.push('                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">');
newLines.push('                  <h3 className="text-xl font-bold text-white uppercase tracking-wider font-display">JEE Test Series Portal</h3>');
newLines.push('                  <div className="flex bg-obsidian/60 p-1 border border-white/5 rounded-lg">');
newLines.push('                    <button');
newLines.push('                      onClick={() => setTestCategory(\'jee-mains\')}');

newLines.push(...lines.slice(520));

fs.writeFileSync(path, newLines.join('\n'));
