name: Deploy to Vercel

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --yes --token=vca_1BQ3ehB32DNR8aebikDPmxXt8raOwuJAYFjlJJL46W4APYDVlB1VGJM7
        env:
          VERCEL_PROJECT_ID: prj_hRzXANWQZoR1KWyXS3FUdZ5TqQwI
          VERCEL_ORG_ID: team_K5DRZR4VYcJnTt1veMacv2DE
